name: Makefile CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2.14
      with:
        key: Ubuntu-22.04

    - name: Build
      run: make

    - name: Test
      run: make test
      
