name: Makefile CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ hashFiles('dependencies-22.04.txt') }}

    - name: Build
      run: make          
      
