name: Makefile CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ccache-${{ hashFiles('dependencies-22.04.txt') }}-2024-08-15T12:38:16.932Z

    - name: Build
      run: make

    - name: Test
      run: make test
      
